/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AppPackage;

import javax.swing.ImageIcon;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;
import org.jfree.util.Rotation;

/**
 *
 * @author AB
 */
public class dashBoardGUI extends javax.swing.JFrame {

    /**
     * Creates new form dashBoardGUI
     */
    int xMouse; int yMouse;
    
    public dashBoardGUI() {
        initComponents();
        this.setIconImage(new ImageIcon( getClass().getResource("customLogo.jpg")).getImage() ); 
        reload.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appClose = new javax.swing.JLabel();
        reload = new javax.swing.JLabel();
        appMin = new javax.swing.JLabel();
        appMove = new javax.swing.JLabel();
        monday = new javax.swing.JTextField();
        tuesday = new javax.swing.JTextField();
        wednesday = new javax.swing.JTextField();
        thursday = new javax.swing.JTextField();
        friday = new javax.swing.JTextField();
        saturday = new javax.swing.JTextField();
        sunday = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        chartDisplay = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appCloseMouseClicked(evt);
            }
        });
        getContentPane().add(appClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 18, 20, 20));

        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/reload-icn.png"))); // NOI18N
        reload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadMouseClicked(evt);
            }
        });
        getContentPane().add(reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 70, -1));

        appMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appMinMouseClicked(evt);
            }
        });
        getContentPane().add(appMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 18, 20, 20));

        appMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                appMoveMouseDragged(evt);
            }
        });
        appMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                appMoveMousePressed(evt);
            }
        });
        getContentPane().add(appMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        monday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monday.setForeground(new java.awt.Color(153, 153, 153));
        monday.setBorder(null);
        monday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mondayKeyReleased(evt);
            }
        });
        getContentPane().add(monday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 260, 40));

        tuesday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuesday.setForeground(new java.awt.Color(153, 153, 153));
        tuesday.setBorder(null);
        tuesday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tuesdayKeyReleased(evt);
            }
        });
        getContentPane().add(tuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 260, 40));

        wednesday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wednesday.setForeground(new java.awt.Color(153, 153, 153));
        wednesday.setBorder(null);
        wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayActionPerformed(evt);
            }
        });
        wednesday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wednesdayKeyReleased(evt);
            }
        });
        getContentPane().add(wednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 260, 40));

        thursday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        thursday.setForeground(new java.awt.Color(153, 153, 153));
        thursday.setBorder(null);
        thursday.setOpaque(false);
        thursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayActionPerformed(evt);
            }
        });
        thursday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thursdayKeyReleased(evt);
            }
        });
        getContentPane().add(thursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 260, 40));

        friday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        friday.setForeground(new java.awt.Color(153, 153, 153));
        friday.setBorder(null);
        friday.setOpaque(false);
        friday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fridayKeyReleased(evt);
            }
        });
        getContentPane().add(friday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 260, 40));

        saturday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saturday.setForeground(new java.awt.Color(153, 153, 153));
        saturday.setBorder(null);
        saturday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saturdayKeyReleased(evt);
            }
        });
        getContentPane().add(saturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 260, 40));

        sunday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sunday.setForeground(new java.awt.Color(153, 153, 153));
        sunday.setBorder(null);
        sunday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sundayKeyReleased(evt);
            }
        });
        getContentPane().add(sunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 260, 40));

        result.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        result.setForeground(new java.awt.Color(102, 102, 102));
        result.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 440, 40));

        chartDisplay.setOpaque(false);
        getContentPane().add(chartDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 440, 300));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 156, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/input.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void appCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_appCloseMouseClicked

    private void appMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMinMouseClicked
        this.setState(dashBoardGUI.ICONIFIED);
    }//GEN-LAST:event_appMinMouseClicked

    private void appMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_appMoveMouseDragged

    private void appMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appMoveMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_appMoveMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           
        for (double i = 0.0; i<= 1.0; i=i+0.1)
        {
            String val = i + "F";
            Float f = Float.valueOf(val);
            this.setOpacity(f);
            
                try
                {
                    Thread.sleep(100);
                }
                catch(Exception e)
                {

                }
            
            
            
        }
        
        
        
    }//GEN-LAST:event_formWindowOpened

    public static boolean isNumeric(String str){
        return str.matches("-?\\d+(\\.\\d+)?");  //match a number with optional '-' and decimal.
    }
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int mondayInt=0; int tuesdayInt=0; int wednesdayInt=0; int thursInt=0;
         int friInt=0; int satInt=0; int sunInt=0;
         
       if(isNumeric(monday.getText()) && isNumeric(tuesday.getText()) && isNumeric(wednesday.getText()) && isNumeric(thursday.getText()) && isNumeric(friday.getText()) && isNumeric(saturday.getText()) && isNumeric(sunday.getText())){
           mondayInt = Integer.parseInt(monday.getText());
           tuesdayInt = Integer.parseInt(tuesday.getText());
           wednesdayInt = Integer.parseInt(wednesday.getText());
           thursInt = Integer.parseInt(thursday.getText());
           friInt = Integer.parseInt(friday.getText());
           satInt = Integer.parseInt(saturday.getText());
           sunInt = Integer.parseInt(sunday.getText());
       
       int average = (mondayInt + tuesdayInt + wednesdayInt + thursInt + friInt + satInt + sunInt)/7;
       
       
       
       
       String output = "Your Average Spending for the week is N" + String.valueOf(average);
   
       result.setText(output);
       
       
       
       PieChart3D demo = new PieChart3D();
        
       String[] titles = {"MON","TUE","WED","THUR","FRI","SAT","SUN"};
       int[] cost = {mondayInt,tuesdayInt,wednesdayInt,thursInt,friInt,satInt,sunInt};
       
          // create a dataset...
        PieDataset dataset = demo.createSampleDataset(titles,cost);
        
        // create the chart...
       JFreeChart chart = demo.createChart(dataset);
        
        // add the chart to a panel...
        final ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));
        chartPanel.setOpaque(false);
        chartDisplay.add(chartPanel);
        reload.setVisible(true);
        
        
        //this.setVisible(false);
       // new dashBoardGUI().setVisible(true);
        
        
        
        
        
       }
       else
       {
           result.setText("None of the Inputs is Permitted to be empty");
       }
           
         
    }//GEN-LAST:event_jLabel2MouseClicked

    
    
    
    private void mondayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mondayKeyReleased
        // TODO add your handling code here:
        if (isNumeric(monday.getText())){
            
        }
        else{
            monday.setText(null);
        }
    }//GEN-LAST:event_mondayKeyReleased

    private void tuesdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuesdayKeyReleased
        if (isNumeric(tuesday.getText())){
            
        }
        else{
            tuesday.setText(null);
        }
    }//GEN-LAST:event_tuesdayKeyReleased

    private void wednesdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wednesdayKeyReleased
         if (isNumeric(wednesday.getText())){
            
        }
        else{
            wednesday.setText(null);
        }
    }//GEN-LAST:event_wednesdayKeyReleased


      
    private void reloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadMouseClicked
        // TODO add your handling code here:
        //this.dispose();
        this.setVisible(false);
        new dashBoardGUI().setVisible(true);
        
    }//GEN-LAST:event_reloadMouseClicked

    private void thursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayActionPerformed
         
    }//GEN-LAST:event_thursdayActionPerformed

    private void thursdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thursdayKeyReleased
         if (isNumeric(thursday.getText())){
            
        }
        else{
            thursday.setText(null);
        }
    }//GEN-LAST:event_thursdayKeyReleased

    private void fridayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fridayKeyReleased
        if (isNumeric(friday.getText())){
            
        }
        else{
            friday.setText(null);
        }

    }//GEN-LAST:event_fridayKeyReleased

    private void saturdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saturdayKeyReleased
                 if (isNumeric(saturday.getText())){
            
        }
        else{
            saturday.setText(null);
        }
    }//GEN-LAST:event_saturdayKeyReleased

    private void sundayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sundayKeyReleased
                 if (isNumeric(sunday.getText())){
            
        }
        else{
            sunday.setText(null);
        }
    }//GEN-LAST:event_sundayKeyReleased

    private void wednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayActionPerformed

    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashBoardGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appClose;
    private javax.swing.JLabel appMin;
    private javax.swing.JLabel appMove;
    private javax.swing.JPanel chartDisplay;
    private javax.swing.JTextField friday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField monday;
    private javax.swing.JLabel reload;
    private javax.swing.JLabel result;
    private javax.swing.JTextField saturday;
    private javax.swing.JTextField sunday;
    private javax.swing.JTextField thursday;
    private javax.swing.JTextField tuesday;
    private javax.swing.JTextField wednesday;
    // End of variables declaration//GEN-END:variables
}
